import type { EAFCDevCard } from '../types';
import { createLeagueMembership } from './leaguesService';

export const PRESET_DEVS: EAFCDevCard[] = [
  {
    id: 'torvalds',
    username: 'torvalds',
    name: 'Linus Torvalds',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1024025?v=4',
    bio: 'Creator of Linux & Git. The Ultimate GOAT of Open Source.',
    location: 'Portland, OR',
    rarity: 'icon',
    position: 'ST',
    positionTitle: 'Grand Architect GOAT',
    countryFlag: '🇫🇮',
    clubName: 'LINUX FOUNDATION',
    footballPosition: 'STRIKER',
    footballPositionTitle: 'Striker (CF/ST)',
    footballPositionBadge: '⚽',
    leagues: [createLeagueMembership('premier', 1), createLeagueMembership('lightning', 1)],
    powerScore: 99500,
    ratings: {
      overall: 99,
      pac: 95,
      sho: 98,
      pas: 99,
      dri: 99,
      def: 96,
      phy: 98,
      sta: 97,
      skl: 99
    },
    stats: {
      username: 'torvalds',
      name: 'Linus Torvalds',
      avatarUrl: 'https://avatars.githubusercontent.com/u/1024025?v=4',
      bio: 'Creator of Linux & Git.',
      location: 'Portland, OR',
      company: 'Linux Foundation',
      publicRepos: 12,
      followers: 215000,
      following: 0,
      createdAt: '2011-09-03',
      commits: 24500,
      stars: 185000,
      prsMerged: 850,
      issuesClosed: 1400,
      forks: 52000,
      streakDays: 365,
      languages: ['C', 'Assembly', 'Shell', 'Make', 'Perl']
    },
    badges: [
      { id: 'goat', name: 'Open Source GOAT', icon: '👑', description: 'Created Linux kernel & Git version control' },
      { id: 'commit-god', name: '20K+ Commits', icon: '⚡', description: 'Over 20,000 commits in core Linux' },
      { id: 'star-master', name: '100K+ Stars', icon: '⭐', description: 'Over 100k repository stars' }
    ],
    skinStyle: 'animated',
    chemistryStyle: 'ARCHITECT',
    createdAt: '2024-01-01'
  },
  {
    id: 'gaearon',
    username: 'gaearon',
    name: 'Dan Abramov',
    avatarUrl: 'https://avatars.githubusercontent.com/u/810438?v=4',
    bio: 'Co-author of Redux and Create React App. React Core Team Alum.',
    location: 'London, UK',
    rarity: 'toty',
    position: 'CAM',
    positionTitle: 'React Mastermind',
    countryFlag: '🇬🇧',
    clubName: 'REACT FC',
    footballPosition: 'MIDFIELDER',
    footballPositionTitle: 'Midfielder (CM/CAM)',
    footballPositionBadge: '🎯',
    leagues: [createLeagueMembership('premier', 2), createLeagueMembership('lightning', 2)],
    powerScore: 28500,
    ratings: {
      overall: 95,
      pac: 92,
      sho: 94,
      pas: 96,
      dri: 98,
      def: 88,
      phy: 94,
      sta: 91,
      skl: 97
    },
    stats: {
      username: 'gaearon',
      name: 'Dan Abramov',
      avatarUrl: 'https://avatars.githubusercontent.com/u/810438?v=4',
      bio: 'Co-author of Redux and Create React App.',
      location: 'London, UK',
      company: 'Bluesky',
      publicRepos: 260,
      followers: 82000,
      following: 12,
      createdAt: '2011-05-25',
      commits: 6400,
      stars: 125000,
      prsMerged: 620,
      issuesClosed: 890,
      forks: 34000,
      streakDays: 310,
      languages: ['JavaScript', 'TypeScript', 'HTML', 'CSS', 'Node.js']
    },
    badges: [
      { id: 'redux', name: 'Redux Creator', icon: '⚛️', description: 'Created Redux state management library' },
      { id: 'react-core', name: 'React Core', icon: '🚀', description: 'Core architect of React UI library' }
    ],
    skinStyle: 'shiny',
    chemistryStyle: 'ENGINE',
    createdAt: '2024-01-01'
  },
  {
    id: 'shadcn',
    username: 'shadcn',
    name: 'shadcn',
    avatarUrl: 'https://avatars.githubusercontent.com/u/124599?v=4',
    bio: 'Creator of shadcn/ui. Beautifully designed components.',
    location: 'USA',
    rarity: 'toty',
    position: 'CF',
    positionTitle: 'UI Perfectionist',
    countryFlag: '🇺🇸',
    clubName: 'SHADCN UI',
    footballPosition: 'STRIKER',
    footballPositionTitle: 'Striker (CF/ST)',
    footballPositionBadge: '⚽',
    leagues: [createLeagueMembership('premier', 3), createLeagueMembership('opensource', 1)],
    powerScore: 24200,
    ratings: {
      overall: 94,
      pac: 94,
      sho: 91,
      pas: 95,
      dri: 97,
      def: 85,
      phy: 92,
      sta: 93,
      skl: 96
    },
    stats: {
      username: 'shadcn',
      name: 'shadcn',
      avatarUrl: 'https://avatars.githubusercontent.com/u/124599?v=4',
      bio: 'Creator of shadcn/ui.',
      location: 'USA',
      company: 'Vercel',
      publicRepos: 45,
      followers: 68000,
      following: 34,
      createdAt: '2009-09-12',
      commits: 4800,
      stars: 85000,
      prsMerged: 420,
      issuesClosed: 560,
      forks: 9200,
      streakDays: 280,
      languages: ['TypeScript', 'TailwindCSS', 'React', 'CSS']
    },
    badges: [
      { id: 'shadcn-ui', name: 'shadcn/ui', icon: '🎨', description: 'Created the most viral UI library in Web Dev' },
      { id: 'design-master', name: 'Design Wizard', icon: '✨', description: 'Pioneered accessible copy-paste components' }
    ],
    skinStyle: 'shiny',
    chemistryStyle: 'SNIPER',
    createdAt: '2024-01-01'
  },
  {
    id: 'mitchellh',
    username: 'mitchellh',
    name: 'Mitchell Hashimoto',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1299?v=4',
    bio: 'Founder of HashiCorp. Creator of Vagrant, Packer, Terraform, Consul.',
    location: 'Seattle, WA',
    rarity: 'hero',
    position: 'GK',
    positionTitle: 'DevOps Titan',
    countryFlag: '🇺🇸',
    clubName: 'HASHICORP',
    footballPosition: 'GOALKEEPER',
    footballPositionTitle: 'Goalkeeper (GK)',
    footballPositionBadge: '🔒',
    leagues: [createLeagueMembership('premier', 4)],
    powerScore: 18400,
    ratings: {
      overall: 92,
      pac: 88,
      sho: 90,
      pas: 94,
      dri: 91,
      def: 93,
      phy: 90,
      sta: 95,
      skl: 95
    },
    stats: {
      username: 'mitchellh',
      name: 'Mitchell Hashimoto',
      avatarUrl: 'https://avatars.githubusercontent.com/u/1299?v=4',
      bio: 'Founder of HashiCorp.',
      location: 'Seattle, WA',
      company: 'Ghostty',
      publicRepos: 180,
      followers: 41000,
      following: 15,
      createdAt: '2008-05-18',
      commits: 9200,
      stars: 62000,
      prsMerged: 780,
      issuesClosed: 950,
      forks: 18000,
      streakDays: 240,
      languages: ['Go', 'Zig', 'Ruby', 'C', 'Shell']
    },
    badges: [
      { id: 'terraform', name: 'Infrastructure Pioneer', icon: '🏗️', description: 'Created Terraform & Vagrant' }
    ],
    skinStyle: 'standard',
    chemistryStyle: 'SHADOW',
    createdAt: '2024-01-01'
  },
  {
    id: 'rauchg',
    username: 'rauchg',
    name: 'Guillermo Rauch',
    avatarUrl: 'https://avatars.githubusercontent.com/u/13041?v=4',
    bio: 'CEO of Vercel. Creator of Socket.io, Next.js pioneer.',
    location: 'San Francisco, CA',
    rarity: 'hero',
    position: 'MGR',
    positionTitle: 'Next.js Visionary',
    countryFlag: '🇦🇷',
    clubName: 'VERCEL',
    footballPosition: 'MANAGER',
    footballPositionTitle: 'Manager (Coach)',
    footballPositionBadge: '👑',
    leagues: [createLeagueMembership('premier', 5), createLeagueMembership('startup', 1)],
    powerScore: 16900,
    ratings: {
      overall: 91,
      pac: 90,
      sho: 89,
      pas: 93,
      dri: 93,
      def: 86,
      phy: 92,
      sta: 88,
      skl: 94
    },
    stats: {
      username: 'rauchg',
      name: 'Guillermo Rauch',
      avatarUrl: 'https://avatars.githubusercontent.com/u/13041?v=4',
      bio: 'CEO of Vercel.',
      location: 'San Francisco, CA',
      company: 'Vercel',
      publicRepos: 120,
      followers: 53000,
      following: 40,
      createdAt: '2009-11-20',
      commits: 5100,
      stars: 54000,
      prsMerged: 390,
      issuesClosed: 480,
      forks: 11000,
      streakDays: 210,
      languages: ['JavaScript', 'TypeScript', 'Node.js', 'Rust']
    },
    badges: [
      { id: 'vercel-ceo', name: 'Vercel Founder', icon: '▲', description: 'Revolutionized web deployment & Next.js ecosystem' }
    ],
    skinStyle: 'standard',
    chemistryStyle: 'HUNTER',
    createdAt: '2024-01-01'
  },
  {
    id: 'sindresorhus',
    username: 'sindresorhus',
    name: 'Sindre Sorhus',
    avatarUrl: 'https://avatars.githubusercontent.com/u/170270?v=4',
    bio: 'Full-time Open Source Developer. 1,000+ npm packages.',
    location: 'Norway',
    rarity: 'gold',
    position: 'CB',
    positionTitle: 'NPM Polymath',
    countryFlag: '🇳🇴',
    clubName: 'OPEN SOURCE FC',
    footballPosition: 'DEFENDER',
    footballPositionTitle: 'Defender (CB/RB/LB)',
    footballPositionBadge: '🛡️',
    leagues: [createLeagueMembership('premier', 6), createLeagueMembership('opensource', 2)],
    powerScore: 9800,
    ratings: {
      overall: 88,
      pac: 92,
      sho: 86,
      pas: 89,
      dri: 87,
      def: 85,
      phy: 84,
      sta: 96,
      skl: 98
    },
    stats: {
      username: 'sindresorhus',
      name: 'Sindre Sorhus',
      avatarUrl: 'https://avatars.githubusercontent.com/u/170270?v=4',
      bio: 'Full-time Open Source Developer.',
      location: 'Norway',
      company: 'Self-employed',
      publicRepos: 1100,
      followers: 51000,
      following: 30,
      createdAt: '2010-01-12',
      commits: 15200,
      stars: 48000,
      prsMerged: 1200,
      issuesClosed: 1600,
      forks: 8500,
      streakDays: 320,
      languages: ['JavaScript', 'TypeScript', 'Swift', 'HTML']
    },
    badges: [
      { id: 'npm-king', name: 'NPM Legend', icon: '📦', description: 'Created over 1,000 open-source packages' }
    ],
    skinStyle: 'standard',
    chemistryStyle: 'ENGINE',
    createdAt: '2024-01-01'
  }
];
