import type { GitFCDevCard } from '../types';

export const PRESET_DEVS: GitFCDevCard[] = [
  {
    id: 'torvalds',
    username: 'torvalds',
    name: 'Linus Torvalds',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1024025?v=4',
    bio: 'Creator of Linux & Git. The Ultimate GOAT of Open Source.',
    location: 'Portland, OR',
    clubName: 'LINUX FOUNDATION',
    countryFlag: '🇫🇮',
    rarity: 'elite',
    rarityTitle: 'ELITE TOTY',
    position: 'ST',
    positionCategory: 'ATT',
    positionTitle: 'Grand Solo Striker',
    archetype: 'Open Source Machine',
    archetypeDescription: 'Created the Linux kernel & Git. The benchmark for open source greatness.',
    powerScore: 99500,
    attributes: {
      att: 99,
      pas: 95,
      def: 96,
      pac: 94,
      dri: 92,
      sho: 98,
      vis: 99,
      sta: 99,
      overall: 98,
      phy: 99,
      skl: 92,
    },
    ratings: {
      att: 99,
      pas: 95,
      def: 96,
      pac: 94,
      dri: 92,
      sho: 98,
      vis: 99,
      sta: 99,
      overall: 98,
      phy: 99,
      skl: 92,
    },
    stats: {
      username: 'torvalds',
      name: 'Linus Torvalds',
      avatarUrl: 'https://avatars.githubusercontent.com/u/1024025?v=4',
      bio: 'Creator of Linux & Git.',
      location: 'Portland, OR',
      company: 'Linux Foundation',
      publicRepos: 12,
      followers: 215000,
      following: 0,
      createdAt: '2011-09-03',
      commits: 24500,
      stars: 185000,
      prsMerged: 850,
      issuesClosed: 1400,
      forks: 52000,
      streakDays: 365,
      languages: ['C', 'Assembly', 'Shell', 'Make', 'Perl'],
    },
    badges: [
      { id: 'goat', name: 'Open Source GOAT', icon: '👑', description: 'Created Linux kernel & Git version control' },
      { id: 'commit-god', name: '20K+ Commits', icon: '⚡', description: 'Over 20,000 commits in core Linux' },
      { id: 'star-master', name: '100K+ Stars', icon: '⭐', description: 'Over 100k repository stars' },
    ],
    strengths: ['Architectural Vision (99)', 'Attack Output (99)'],
    weaknesses: ['Language Versatility (92)', 'Sprint Pace (94)'],
    playstyle: 'Legendary direct play: world-defining C architecture, zero overhead, and unparalleled longevity.',
    createdAt: '2024-01-01',
  },
  {
    id: 'gaearon',
    username: 'gaearon',
    name: 'Dan Abramov',
    avatarUrl: 'https://avatars.githubusercontent.com/u/810438?v=4',
    bio: 'Co-author of Redux and Create React App. React Core Team Alum.',
    location: 'London, UK',
    clubName: 'REACT FC',
    countryFlag: '🇬🇧',
    rarity: 'elite',
    rarityTitle: 'ELITE TOTY',
    position: 'CAM',
    positionCategory: 'MID',
    positionTitle: 'Master Playmaker',
    archetype: 'Master Playmaker',
    archetypeDescription: 'Shaped the modern frontend ecosystem with Redux, Hot Reloading, and React.',
    powerScore: 84000,
    attributes: {
      att: 91,
      pas: 96,
      def: 88,
      pac: 89,
      dri: 95,
      sho: 92,
      vis: 97,
      sta: 93,
      overall: 94,
      phy: 93,
      skl: 95,
    },
    ratings: {
      att: 91,
      pas: 96,
      def: 88,
      pac: 89,
      dri: 95,
      sho: 92,
      vis: 97,
      sta: 93,
      overall: 94,
      phy: 93,
      skl: 95,
    },
    stats: {
      username: 'gaearon',
      name: 'Dan Abramov',
      avatarUrl: 'https://avatars.githubusercontent.com/u/810438?v=4',
      bio: 'Working on React.',
      location: 'London, UK',
      company: 'Meta / Independent',
      publicRepos: 260,
      followers: 86000,
      following: 172,
      createdAt: '2011-05-25',
      commits: 6800,
      stars: 94000,
      prsMerged: 620,
      issuesClosed: 980,
      forks: 24000,
      streakDays: 240,
      languages: ['JavaScript', 'TypeScript', 'CSS', 'HTML', 'Markdown'],
    },
    badges: [
      { id: 'react-icon', name: 'React Pioneer', icon: '⚛️', description: 'Redux & Create React App co-author' },
      { id: 'community-pillar', name: 'Dev Icon', icon: '👑', description: '80K+ developer followers' },
    ],
    strengths: ['Architectural Vision (97)', 'Collaboration & PRs (96)'],
    weaknesses: ['Sprint Pace (89)', 'Bug Fixing & Defense (88)'],
    playstyle: 'Tiki-taka state management: surgical pull requests and developer experience refinement.',
    createdAt: '2024-01-01',
  },
  {
    id: 'antfu',
    username: 'antfu',
    name: 'Anthony Fu',
    avatarUrl: 'https://avatars.githubusercontent.com/u/11247099?v=4',
    bio: 'Vue / Nuxt / Vite / UnoCSS / Vitest core team. Open source maniac.',
    location: 'Tokyo, Japan',
    clubName: 'UNJS & VUE FC',
    countryFlag: '🇯🇵',
    rarity: 'elite',
    rarityTitle: 'ELITE TOTY',
    position: 'LW',
    positionCategory: 'ATT',
    positionTitle: 'Velocity Winger',
    archetype: 'Open Source Machine',
    archetypeDescription: 'Fastest shipping velocity in JavaScript tooling with dozens of viral packages.',
    powerScore: 92000,
    attributes: {
      att: 98,
      pas: 96,
      def: 91,
      pac: 99,
      dri: 97,
      sho: 95,
      vis: 94,
      sta: 98,
      overall: 96,
      phy: 98,
      skl: 97,
    },
    ratings: {
      att: 98,
      pas: 96,
      def: 91,
      pac: 99,
      dri: 97,
      sho: 95,
      vis: 94,
      sta: 98,
      overall: 96,
      phy: 98,
      skl: 97,
    },
    stats: {
      username: 'antfu',
      name: 'Anthony Fu',
      avatarUrl: 'https://avatars.githubusercontent.com/u/11247099?v=4',
      bio: 'Open source maniac.',
      location: 'Tokyo, Japan',
      company: 'NuxtLabs / Independent',
      publicRepos: 450,
      followers: 32000,
      following: 80,
      createdAt: '2015-02-14',
      commits: 18000,
      stars: 75000,
      prsMerged: 950,
      issuesClosed: 1200,
      forks: 15000,
      streakDays: 400,
      languages: ['TypeScript', 'JavaScript', 'Vue', 'CSS', 'Rust'],
    },
    badges: [
      { id: 'oss-machine', name: 'OSS Speedster', icon: '🚀', description: 'Unmatched shipping velocity' },
      { id: 'vite-creator', name: 'Tooling Visionary', icon: '⚡', description: 'Core team for Vite & Vue ecosystem' },
    ],
    strengths: ['Sprint Pace (99)', 'Attack Output (98)'],
    weaknesses: ['Defense & Tactics (91)', 'Collaboration (94)'],
    playstyle: 'Ultra-high-speed development: constant innovation with minimal friction.',
    createdAt: '2024-01-01',
  },
  {
    id: 'mitchellh',
    username: 'mitchellh',
    name: 'Mitchell Hashimoto',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1299?v=4',
    bio: 'Founder of HashiCorp. Creator of Vagrant, Packer, Terraform, Consul.',
    location: 'Seattle, WA',
    clubName: 'HASHICORP / GHOSTTY',
    countryFlag: '🇺🇸',
    rarity: 'epic',
    rarityTitle: 'EPIC GOLD',
    position: 'GK',
    positionCategory: 'GK',
    positionTitle: 'Infrastructure Guardian',
    archetype: 'DevOps Titan',
    archetypeDescription: 'Built Terraform, Vagrant, Consul, and Ghostty — rock-solid infrastructure.',
    powerScore: 78000,
    attributes: {
      att: 88,
      pas: 92,
      def: 96,
      pac: 86,
      dri: 90,
      sho: 89,
      vis: 95,
      sta: 95,
      overall: 92,
      phy: 95,
      skl: 90,
    },
    ratings: {
      att: 88,
      pas: 92,
      def: 96,
      pac: 86,
      dri: 90,
      sho: 89,
      vis: 95,
      sta: 95,
      overall: 92,
      phy: 95,
      skl: 90,
    },
    stats: {
      username: 'mitchellh',
      name: 'Mitchell Hashimoto',
      avatarUrl: 'https://avatars.githubusercontent.com/u/1299?v=4',
      bio: 'Founder of HashiCorp.',
      location: 'Seattle, WA',
      company: 'Ghostty',
      publicRepos: 180,
      followers: 41000,
      following: 15,
      createdAt: '2008-05-18',
      commits: 9200,
      stars: 62000,
      prsMerged: 780,
      issuesClosed: 950,
      forks: 18000,
      streakDays: 240,
      languages: ['Go', 'Zig', 'Ruby', 'C', 'Shell'],
    },
    badges: [
      { id: 'terraform', name: 'Infrastructure Pioneer', icon: '🏗️', description: 'Created Terraform & Vagrant' },
      { id: 'ghostty', name: 'Ghostty Creator', icon: '👻', description: 'Built fast native terminal in Zig' },
    ],
    strengths: ['Bug Fixing & Defense (96)', 'Architectural Vision (95)'],
    weaknesses: ['Sprint Pace (86)', 'Attack Output (88)'],
    playstyle: 'Impenetrable defense: deep systems engineering, zero downtime, and robust infrastructure.',
    createdAt: '2024-01-01',
  },
  {
    id: 'rauchg',
    username: 'rauchg',
    name: 'Guillermo Rauch',
    avatarUrl: 'https://avatars.githubusercontent.com/u/13041?v=4',
    bio: 'CEO of Vercel. Creator of Next.js ecosystem & Socket.io.',
    location: 'San Francisco, CA',
    clubName: 'VERCEL FC',
    countryFlag: '🇦🇷',
    rarity: 'epic',
    rarityTitle: 'EPIC GOLD',
    position: 'CAM',
    positionCategory: 'MID',
    positionTitle: 'Web Ecosystem Playmaker',
    archetype: 'System Architect',
    archetypeDescription: 'Connecting the global web through frontend cloud architecture and real-time tech.',
    powerScore: 76000,
    attributes: {
      att: 89,
      pas: 95,
      def: 84,
      pac: 90,
      dri: 93,
      sho: 91,
      vis: 98,
      sta: 90,
      overall: 92,
      phy: 90,
      skl: 93,
    },
    ratings: {
      att: 89,
      pas: 95,
      def: 84,
      pac: 90,
      dri: 93,
      sho: 91,
      vis: 98,
      sta: 90,
      overall: 92,
      phy: 90,
      skl: 93,
    },
    stats: {
      username: 'rauchg',
      name: 'Guillermo Rauch',
      avatarUrl: 'https://avatars.githubusercontent.com/u/13041?v=4',
      bio: 'CEO @vercel',
      location: 'San Francisco, CA',
      company: 'Vercel',
      publicRepos: 240,
      followers: 54000,
      following: 120,
      createdAt: '2008-06-03',
      commits: 6200,
      stars: 48000,
      prsMerged: 510,
      issuesClosed: 640,
      forks: 9200,
      streakDays: 200,
      languages: ['JavaScript', 'TypeScript', 'HTML', 'CSS', 'C++'],
    },
    badges: [
      { id: 'nextjs-founder', name: 'Web Cloud Titan', icon: '▲', description: 'Pioneered Next.js & Frontend Cloud' },
      { id: 'socketio', name: 'Realtime Pioneer', icon: '⚡', description: 'Created Socket.io' },
    ],
    strengths: ['Architectural Vision (98)', 'Collaboration & PRs (95)'],
    weaknesses: ['Bug Fixing & Defense (84)', 'Attack Output (89)'],
    playstyle: 'Visionary leadership: orchestrating modern web standards with speed and precision.',
    createdAt: '2024-01-01',
  },
];
